In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([1, 5], dtype = tf.int64)
print(a)
print(a.dtype)
print(a.shape)

tf.Tensor([1 5], shape=(2,), dtype=int64)
<dtype: 'int64'>
(2,)


> shape中逗号隔开几个数字，就是几维。

In [3]:
import numpy as np

In [6]:
a = np.arange(0, 5)
b = tf.convert_to_tensor(a, dtype = tf.int64)
print(a)
print(b)

[0 1 2 3 4]
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)


> tf.convert_to_tensor将numpy格式转为张量，两个参数分别是数据名和类型。

## 如何创建一个张量

In [7]:
a = tf.zeros([2, 2])
b = tf.ones(4)
c = tf.fill([3,3], 9)
print(a)
print(b)
print(c)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor([1. 1. 1. 1.], shape=(4,), dtype=float32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


In [9]:
a = tf.random.normal([2, 2], mean = 0.5, stddev = 1)
b = tf.random.truncated_normal([2, 2], mean = 0.5, stddev = 1)
print(a)
print(b)

tf.Tensor(
[[0.44468048 0.5114101 ]
 [0.3226295  2.6347578 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.3241434  1.270691  ]
 [0.35826704 0.04361027]], shape=(2, 2), dtype=float32)


> random.normal的参数分别是维度，均值，标准差。random.truncated_normal可以保证生成的随机数在正负2个标准差之内。

In [14]:
a = tf.random.uniform([2, 2], minval = 0, maxval = 1)
print(a)

tf.Tensor(
[[0.11616158 0.1039319 ]
 [0.87229264 0.4636017 ]], shape=(2, 2), dtype=float32)


> random.uniform的参数分别是维度，最小值，最大值，生成一个左闭右开区间的服从均匀分布的指定维度的张量。

In [15]:
x1 = tf.constant([1, 2, 3], dtype = tf.int64)
x2 = tf.cast(x1, dtype = tf.int32)
print(tf.reduce_min(x2), tf.reduce_max(x2))

tf.Tensor(1, shape=(), dtype=int32) tf.Tensor(3, shape=(), dtype=int32)


> cast表示强制类型转换，参数分别是张量名和要转为的类型。

> reduce_min找出向量所有元素里的最小值，max找出最大值。

In [16]:
x = tf.constant([[1, 2, 3], [4, 5, 6]], dtype = tf.int64)
x1 = tf.reduce_mean(x, axis = 0)
x2 = tf.reduce_sum(x, axis = 1)
print(x1, x2)

tf.Tensor([2 3 4], shape=(3,), dtype=int64) tf.Tensor([ 6 15], shape=(2,), dtype=int64)


> axis指定操作方向。axis等于几，表示对哪个维度进行操作。对于二维数组来说，axis=0表示经度方向（对第一个维度操作，也就是跨行），axis=1表示纬度方向（对第二维操作，也就是跨列）。

> reduce_mean和sum分别表示求平均值和和

In [18]:
a = tf.Variable(tf.constant(5, dtype = tf.int64))
print(a)

<tf.Variable 'Variable:0' shape=() dtype=int64, numpy=5>


> Variable可以将张量标记为可训练的，会在反向传播中记录梯度信息。神经网络训练中，常用该函数标记训练参数。

In [20]:
x = tf.ones([1, 3])
y = tf.fill([1, 3], 7.)
r1 = tf.add(x, y)
r2 = tf.subtract(x, y)
r3 = tf.multiply(x, y)
r4 = tf.divide(x, y)
print(r1, r2, r3, r4)

tf.Tensor([[8. 8. 8.]], shape=(1, 3), dtype=float32) tf.Tensor([[-6. -6. -6.]], shape=(1, 3), dtype=float32) tf.Tensor([[7. 7. 7.]], shape=(1, 3), dtype=float32) tf.Tensor([[0.14285715 0.14285715 0.14285715]], shape=(1, 3), dtype=float32)


In [21]:
print(tf.square(y))
print(tf.pow(y, 2))
print(tf.sqrt(y))

tf.Tensor([[49. 49. 49.]], shape=(1, 3), dtype=float32)
tf.Tensor([[49. 49. 49.]], shape=(1, 3), dtype=float32)
tf.Tensor([[2.6457512 2.6457512 2.6457512]], shape=(1, 3), dtype=float32)


In [23]:
z = tf.fill([3, 1], 8.)
print(tf.matmul(y, z))

tf.Tensor([[168.]], shape=(1, 1), dtype=float32)


In [27]:
x = tf.constant([12, 15, 17,10])
label = tf.constant([0, 1, 1, 0])
dataset = tf.data.Dataset.from_tensor_slices((x, label))
print(dataset)
for e in dataset:
    print(e)

<TensorSliceDataset shapes: ((), ()), types: (tf.int32, tf.int32)>
(<tf.Tensor: id=106, shape=(), dtype=int32, numpy=12>, <tf.Tensor: id=107, shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: id=108, shape=(), dtype=int32, numpy=15>, <tf.Tensor: id=109, shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: id=110, shape=(), dtype=int32, numpy=17>, <tf.Tensor: id=111, shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: id=112, shape=(), dtype=int32, numpy=10>, <tf.Tensor: id=113, shape=(), dtype=int32, numpy=0>)


> from_tensor_slices用于给特征和标签配对。