代码、图片均来源于中国大学MOOC曹健老师《人工智能实践：TensorFlow笔记2》，地址：https://www.icourse163.org/learn/PKU-1002536002?tid=1452937471#/learn/announce ，部分代码在我练习过程中有修改。

In [5]:
import tensorflow as tf
import numpy as np

In [3]:
a = tf.constant([1, 2, 3, 4])
b = tf.constant([4, 3, 2, 1])
c = tf.where(tf.greater(a, b), a, b)
print(c)

tf.Tensor([4 3 3 4], shape=(4,), dtype=int32)


条件语句为真返回true，条件语句为假返回false

In [7]:
rdm = np.random.RandomState(seed = 1)
a = rdm.rand()
b = rdm.rand(3, 4)
print(a, b)

0.417022004702574 [[7.20324493e-01 1.14374817e-04 3.02332573e-01 1.46755891e-01]
 [9.23385948e-02 1.86260211e-01 3.45560727e-01 3.96767474e-01]
 [5.38816734e-01 4.19194514e-01 6.85219500e-01 2.04452250e-01]]


np.random.RandomState,rand(维度)返回一个指定维度的[0, 1)之间的随机数。

In [10]:
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])
c = np.vstack((a, b))
print(c)

[[1 2 3]
 [3 4 5]]


vstack把两个数组按垂直方向叠加。

In [16]:
x, y = np.mgrid[1:6:1, 2:4:1]
print(x)
print(y)
grid = np.c_[x.ravel(), y.ravel()]
print(x, y)
print(grid)

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]
[[2 3]
 [2 3]
 [2 3]
 [2 3]
 [2 3]]
[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]] [[2 3]
 [2 3]
 [2 3]
 [2 3]
 [2 3]]
[[1 2]
 [1 3]
 [2 2]
 [2 3]
 [3 2]
 [3 3]
 [4 2]
 [4 3]
 [5 2]
 [5 3]]


np.mgrid返回若干组维度相同的等差数组，起始值，结束值，步长，左闭右开区间。x.ravel将x变为一维数组，np.c_[]使返回的间隔数值点配对。
感觉这里mooc里解释的有问题。mgrid应该是返回多维结构，常见的如2D图形，3D图形。第一个参数表示k维，它朝右扩展；第二个参数表示b维，它朝下扩展。

In [18]:
w = tf.Variable(tf.constant(5, dtype = tf.float32))
LR_BASE = 0.2
LR_DECAY = 0.99
LR_STEP = 1
epoch = 40

for epoch in range(epoch):
    lr = LR_BASE * LR_DECAY ** (epoch / LR_STEP)
    with tf.GradientTape() as tape:
        loss = tf.square(w + 1)
    grads = tape.gradient(loss, w)
    w.assign_sub(lr * w)
    print("after %s epoch, w is %f, loss is %f, lr is %f" % (epoch, w.numpy(), loss, lr))

after 0 epoch, w is 4.000000, loss is 36.000000, lr is 0.200000
after 1 epoch, w is 3.208000, loss is 25.000000, lr is 0.198000
after 2 epoch, w is 2.579168, loss is 17.707266, lr is 0.196020
after 3 epoch, w is 2.078655, loss is 12.810442, lr is 0.194060
after 4 epoch, w is 1.679305, loss is 9.478117, lr is 0.192119
after 5 epoch, w is 1.359905, loss is 7.178678, lr is 0.190198
after 6 epoch, w is 1.103840, loss is 5.569150, lr is 0.188296
after 7 epoch, w is 0.898070, loss is 4.426144, lr is 0.186413
after 8 epoch, w is 0.732332, loss is 3.602670, lr is 0.184549
after 9 epoch, w is 0.598532, loss is 3.000975, lr is 0.182703
after 10 epoch, w is 0.490272, loss is 2.555306, lr is 0.180876
after 11 epoch, w is 0.402480, loss is 2.220911, lr is 0.179068
after 12 epoch, w is 0.331130, loss is 1.966951, lr is 0.177277
after 13 epoch, w is 0.273015, loss is 1.771906, lr is 0.175504
after 14 epoch, w is 0.225579, loss is 1.620567, lr is 0.173749
after 15 epoch, w is 0.186777, loss is 1.50204

![](https://www.wangliguang.cn/wp-content/uploads/2020/03/批注-2020-03-17-162014.png)

In [27]:
SEED = 23455

rdm = np.random.RandomState(seed = SEED)
x = rdm.rand(32, 2)
y_ = [[x1 + x2 + (rdm.rand()/10-0.05)] for (x1, x2) in x]
x = tf.cast(x, dtype = tf.float32)

w1 = tf.Variable(tf.random.normal([2, 1], stddev = 1, seed = 1))

epoch = 15000
lr = 0.002

for epoch in range(epoch):
    with tf.GradientTape() as tape:
        y = tf.matmul(x, w1)
        loss = tf.reduce_mean(tf.square(y_ - y))
    grads = tape.gradient(loss, w1)
    w1.assign_sub(lr * grads)
    if epoch % 500 == 0:
        print(w1.numpy())

[[ 0.34875482]
 [-1.9341799 ]]
[[ 1.3077168 ]
 [-0.44903868]]
[[1.535863  ]
 [0.13267002]]
[[1.5353235]
 [0.3959133]]
[[1.4718056]
 [0.5399524]]
[[1.3985068]
 [0.6339418]]
[[1.3312589]
 [0.7029188]]
[[1.2737054 ]
 [0.75676817]]
[[1.225691  ]
 [0.80002147]]
[[1.1860368]
 [0.8351922]]
[[1.1534184 ]
 [0.86393774]]
[[1.1266327]
 [0.8874816]]
[[1.1046516]
 [0.9067821]]
[[1.086618 ]
 [0.9226095]]
[[1.071824 ]
 [0.9355909]]
[[1.059689 ]
 [0.9462385]]
[[1.049735  ]
 [0.95497227]]
[[1.0415702 ]
 [0.96213627]]
[[1.0348728 ]
 [0.96801233]]
[[1.0293794 ]
 [0.97283214]]
[[1.0248733]
 [0.9767857]]
[[1.0211773]
 [0.9800288]]
[[1.0181456]
 [0.9826888]]
[[1.0156586]
 [0.9848706]]
[[1.0136193]
 [0.9866603]]
[[1.0119456 ]
 [0.98812854]]
[[1.010574 ]
 [0.9893326]]
[[1.0094488]
 [0.9903197]]
[[1.0085258 ]
 [0.99113035]]
[[1.007766]
 [0.991794]]


In [28]:
y_ = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0]])
y = np.array([[12, 3, 2], [3, 10, 1], [1, 2, 5], [4, 6.5, 1.2], [3, 6, 1]])
y_pro = tf.nn.softmax(y)
loss1 = tf.losses.categorical_crossentropy(y_, y_pro)
loss2 = tf.nn.softmax_cross_entropy_with_logits(y_, y)
print(loss1, loss2)

tf.Tensor(
[1.68795487e-04 1.03475622e-03 6.58839038e-02 2.58349207e+00
 5.49852354e-02], shape=(5,), dtype=float64) tf.Tensor(
[1.68795487e-04 1.03475622e-03 6.58839038e-02 2.58349207e+00
 5.49852354e-02], shape=(5,), dtype=float64)


In [29]:
y_ = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0]])
y = np.array([[12, 3, 2], [3, 10, 1], [1, 2, 5], [4, 6.5, 1.2], [3, 6, 1]])
y_pro = tf.nn.softmax(y)
loss1 = tf.losses.categorical_crossentropy(y_, y_pro)
loss2 = tf.nn.softmax_cross_entropy_with_logits(y_, y)
print(loss1, loss2)

tf.Tensor(
[1.68795487e-04 1.03475622e-03 6.58839038e-02 2.58349207e+00
 5.49852354e-02], shape=(5,), dtype=float64) tf.Tensor(
[1.68795487e-04 1.03475622e-03 6.58839038e-02 2.58349207e+00
 5.49852354e-02], shape=(5,), dtype=float64)


In [1]:
y_ = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0]])
y = np.array([[12, 3, 2], [3, 10, 1], [1, 2, 5], [4, 6.5, 1.2], [3, 6, 1]])
y_pro = tf.nn.softmax(y)
loss1 = tf.losses.categorical_crossentopy(y_, y_pro)
loss2 = tf.nn.softmax_cross_entropy_with_logits(y_, y_pro)
print(loss1, loss2)

NameError: name 'np' is not defined